/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `crypt' function. */
#define HAVE_CRYPT 1

/* Define to 1 if you have the <crypt.h> header file. */
#define HAVE_CRYPT_H 1

/* Define to 1 if Cyrus-SASL Version 1 is installed */
/* #undef HAVE_CYRUS_SASL_V1 */

/* Define to 1 if Cyrus-SASL Version 2 is installed */
/* #undef HAVE_CYRUS_SASL_V2 */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if ELOOP is an usable constant. */
#define HAVE_ELOOP 1

/* Define to 1 if EOVERFLOW is an usable constant. */
#define HAVE_EOVERFLOW 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `freeaddrinfo' function. */
#define HAVE_FREEADDRINFO 1

/* Define to 1 if you have the `getaddrinfo' function. */
#define HAVE_GETADDRINFO 1

/* Define to 1 if you have the `gethostbyname_r' function. */
#define HAVE_GETHOSTBYNAME_R 1

/* Define to 1 if gethostbyname_r() is part of glibc */
#define HAVE_GNU_GETHOSTBYNAME_R 1

/* Define to 1 if you have the `inet_ntop' function. */
#define HAVE_INET_NTOP 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if IPv6 is available. */
#define HAVE_IPV6 1

/* Define to 1 if you have the `make_scrambled_password_323' function. */
#define HAVE_MAKE_SCRAMBLED_PASSWORD_323 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the `MD5Data' function. */
/* #undef HAVE_MD5DATA */

/* Define to 1 if you have the <md5.h> header file. */
#define HAVE_MD5_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to `1' if you have the <mysql.h> header file. */
#define HAVE_MYSQL_H 1

/* Define to 1 if you have the `mysql_real_escape_string' function. */
#define HAVE_MYSQL_REAL_ESCAPE_STRING 1

/* Define to 1 if you have the `mysql_real_query' function. */
#define HAVE_MYSQL_REAL_QUERY 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if OpenSSL library is installed */
#define HAVE_OPENSSL 1

/* Define to 1 if you have the <opensslv.h> header file. */
#define HAVE_OPENSSLV_H 1

/* Define to 1 if you have the <pam_appl.h> header file. */
#define HAVE_PAM_APPL_H 1

/* Define to 1 if PAM defines PAM_CONV_AGAIN constant. */
#define HAVE_PAM_CONV_AGAIN 1

/* Define to 1 if PAM defines PAM_INCOMPLETE constant. */
#define HAVE_PAM_INCOMPLETE 1

/* Define to 1 if PAM defines PAM_NEW_AUTHTOK_REQD constant. */
#define HAVE_PAM_NEW_AUTHTOK_REQD 1

/* Define to 1 if md5.h in the include path is derived from cyrus-sasl_v1
   package */
/* #undef HAVE_SASL_MD5_H */

/* Define to 1 if Solaris's libmd5 is available */
/* #undef HAVE_SOLARIS_LIBMD5 */

/* Define to 1 if md5.h in the include path is Solaris's */
#define HAVE_SOLARIS_MD5_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if cpp supports the ANSI # stringizing operator. */
#define HAVE_STRINGIZE 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if the system has the type `struct in6_addr'. */
#define HAVE_STRUCT_IN6_ADDR 1

/* Define to 1 if the system has the type `struct sockaddr_in6'. */
#define HAVE_STRUCT_SOCKADDR_IN6 1

/* Define to 1 if gethostbyname_r() is part of SUN libc */
/* #undef HAVE_SUNOS_GETHOSTBYNAME_R */

/* Define to 1 if you have the <syslog.h> header file. */
#define HAVE_SYSLOG_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Define to 1 if the implementation does not define PAM_AUTHTOK_RECOVER_ERR
   */
/* #undef LINUX_PAM_CONST_BUG */

/* Name of package */
#define PACKAGE "pam_mysql"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "pam_mysql"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pam_mysql 0.7RC1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pam_mysql"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.7RC1"

/* Define to `const' if the 2nd arg of pam_conv.conv takes const pointer. */
#define PAM_CONV_CONST 

/* Define to `const' if the 2nd arg of pam_get_data() takes const pointer */
#define PAM_GET_DATA_CONST const

/* Define to `const' if the 2nd arg of pam_get_item() takes const pointer */
#define PAM_GET_ITEM_CONST const

/* Define to `const' if the 2nd arg of pam_get_user() takes const pointer */
#define PAM_GET_USER_CONST const

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.7RC1"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */
